### PR TITLE
Updated README.md + Added CORE and API folders.

### PR DESCRIPTION
**Pull request by Consianimis**
Added overview, status, license, and contribution content.

### CODE REVIEW

**Review by OASIS-OP-Admin — CHANGES_REQUESTED** [review]
Please make OASIS all capital letters

Rather than use 'OASIS Standards' in the description - a designation that can't be applied until after the members of OASIS approve it - please use "OASIS Specifications" or "Specifications." That accomplishes the same goal of identifying the work being done as technical specifications

**Comment by Consianimis** [comment]
@OASIS-OP-Admin - I have made the requested changes. Could you please review and approve ? Thanks.

**Comment by Consianimis** [comment]
Note - As the PR was still open I took the opportunity to add the API and CORE folders. They contain the OASIS templates that we started working with.

**Review by Therecanbeonlyone1969 — APPROVED** [review]

**Review by OASIS-OP-Admin — APPROVED** [review]

**Comment by OASIS-OP-Admin** [comment]
I reviewed and approved.

**Comment by Consianimis** [comment]
@Therecanbeonlyone1969 - I linked the PR to the issue. @kthomas - can you please approve?

**Pull request merged**
