### PR TITLE
1st draft of DLT requirements for a Baseline Protocol Instance

### PR DESCRIPTION
**Pull request by Therecanbeonlyone1969**
From the intro:

Distributed Ledger Technology (DLT) is the foundational enabler of a Baseline Protocol Instance (BPI) with no or limited trust assumptions. The requirements that a DLT must satisfy for it to be used in a BPI as defined in the Baseline Standard fall in the following categories:
1. Security
2. Privacy
3. Scalability
4. Interoperability
5. Network
6. Consensus
7. Virtual State Machine
8. Data Integrity & Transaction Completeness 
9. Integration to External Applications

In the requirements below, we will refer to "The DLT" to mean a DLT chosen by the participants to implement a BPI.

As the title says, this is the 1st draft, please, comment, and vigorously discuss the PR.

### CODE REVIEW

**Review by humbitious — CHANGES_REQUESTED** [review]
Looks like solid work. A couple notes:
1) Should we be using "supplier" and "buyer" as the canonical actors in the diagrams and language?  Should they not be more abstracted as "Initiator" and "Receiver(s)"?  (We currently only have bilateral worksteps, so technically we only have "Receiver" -- "Recipient?" -- but the baseline protocol does contemplate multiparty worksteps where there would be multiple Recipients.

2) Can we name "SOR" for "System-of-Record" or best to keep spelling it out?  Should we make "SOR" definition more explicit? Are there any kinds of traditional record keeping systems or structures that would not be appropriate for baselining? (I can't think of any right now, but others might have thoughts on this.)

3) We say "DLT" in the doc.  First, is there anything in particular about a DLT that is required where a generalized state machine would not suffice? And Second, if the primary distinction between a DLT and "State Machine" that makes the former appropriate here as a requirement (rather than a convention borne from the people like us who happen to be "DLT" people and so happen to have implemented all this in blockchain technology) is its nature as an "always-on state machine maintained as public good that maximizes resistance to tampering or allowing a group to lock one out of valid operations, in particular so that one need not stand up a new private state machine for every partnership or consortium and so that workflows constructed between different workgroups can be made to interoperate and validate cross-workflow worksteps, then we should stipulate that there is little point in using the baseline protocol approach (at least in production...stage it wherever you like for dev and testing -- and for getting pointy haired managers comfortable) unless one were intending to use a public Mainnet that meets the stated requirements of tamper resistance and availability.

**Comment by Therecanbeonlyone1969** [comment]
> Looks like solid work. A couple notes:
> 
> 1. Should we be using "supplier" and "buyer" as the canonical actors in the diagrams and language?  Should they not be more abstracted as "Initiator" and "Receiver(s)"?  (We currently only have bilateral worksteps, so technically we only have "Receiver" -- "Recipient?" -- but the baseline protocol does contemplate multiparty worksteps where there would be multiple Recipients.

@humbitious ... it is not. The figure is for a specific example and not canonicalized. The canonicalized picture is the reference architecture in Fig 2.

> 2. Can we name "SOR" for "System-of-Record" or best to keep spelling it out?  Should we make "SOR" definition more explicit? Are there any kinds of traditional record keeping systems or structures that would not be appropriate for baselining? (I can't think of any right now, but others might have thoughts on this.)

@humbitious system-of-record is in the glossary, and yes we could then use SOR as a short-hand aka TLA. I have no opinion on it. Unless it is critical to change, I would leave it for now.

> 3. We say "DLT" in the doc.  First, is there anything in particular about a DLT that is required where a generalized state machine would not suffice? And Second, if the primary distinction between a DLT and "State Machine" that makes the former appropriate here as a requirement (rather than a convention borne from the people like us who happen to be "DLT" people and so happen to have implemented all this in blockchain technology) is its nature as an "always-on state machine maintained as public good that maximizes resistance to tampering or allowing a group to lock one out of valid operations, in particular so that one need not stand up a new private state machine for every partnership or consortium and so that workflows constructed between different workgroups can be made to interoperate and validate cross-workflow worksteps, then we should stipulate that there is little point in using the baseline protocol approach (at least in production...stage it wherever you like for dev and testing -- and for getting pointy haired managers comfortable) unless one were intending to use a public Mainnet that meets the stated requirements of tamper resistance and availability.

@humbitious your statement in the "..." is for a permissionless DLT, you just missed the distributed bit. And DLT is an established word with a well-defined meaning. So do you want to mandate that a DLT has to be permissionless? That is fine. Right now we are not specifying that but it is a minor change, one word plus a glossary entry for permissionless. I just wanna say that this might cause adoption issues. We could alternatively add another requirement

**[DXX]** The DLT utilized by a BPI SHOULD be permissionless.

And be done with it and add the definition of permissionless to the glossary.

Thoughts?

**Review by humbitious — COMMENTED** [review]
Suggested language:

The Common Frame of Reference (CFR) (glossary entry) MUST be a state machine that all parties agree is acceptable to them for the storing and management of baseline proofs. During testing and staging, or for other use cases where the level of decentralization and tamper-resistance of the CFR is not important, one CAN implement the baseline protocol on whatever state machine suits the purpose, so long as all counterparties involved are informed, understand and agree to that implementation choice. However, in the case of baselining commercial agreements where the integrity and tamper resistance of the proofs is paramount in order to provide assurance to auditors, regulators and other governance entities, and where the ability for counterparties to conduct valid operations without hinderance is also paramount, the CFR used MUST be implemented on a DLT with the properties herein.  These are summarized as "A state machine maintained as a public good that is always-on, pay-as-you-go, and which strongly resists anyone gaining control over the system, locking others out of valid operations, or tampering with the established record."

**Comment by Therecanbeonlyone1969** [comment]
@Consianimis @kthomas ... changes implemented as agreed upon during the 5/27/2021 Standards meeting. Please, verify and approve the PR as soon as possible. There are no more blockers.

**Review by Consianimis — APPROVED** [review]

**Review by humbitious — APPROVED** [review]

**Review by kthomas — APPROVED** [review]

**Pull request merged**
